---
development:
  cloud_name: drykvzbd2
  api_key: '683728431132989'
  api_secret: JhDYEtzFDjxfCL7sE6irkhmIAxw
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: drykvzbd2
  api_key: '683728431132989'
  api_secret: JhDYEtzFDjxfCL7sE6irkhmIAxw
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: drykvzbd2
  api_key: '683728431132989'
  api_secret: JhDYEtzFDjxfCL7sE6irkhmIAxw
  enhance_image_tag: true
  static_image_support: false
